Bump xdr
stellar/homebrew-tap pull request #32
Opened 2023-10-10 13:24 UTC by sisuresh

2023-10-10 13:26 UTC, sisuresh commented
@leighmcculloch what should we do about the `StellarCoreFuturenet` formula? Should we delete it or update/rename it to just reflect latest stellar-core. I don't think anyone is using it, so maybe deleting makes sense?

2023-10-11 18:52 UTC, leighmcculloch requested changes

2023-10-11 18:52 UTC, leighmcculloch commented on Formula/stellar-xdr.rb
> +    assert_match "stellar-xdr v20.0.0-rc1", shell_output("#{bin}/stellar-xdr version")
```suggestion
    assert_match "stellar-xdr 20.0.0-rc1", shell_output("#{bin}/stellar-xdr version")
```

2023-10-11 18:53 UTC, leighmcculloch commented
> @leighmcculloch what should we do about the `StellarCoreFuturenet` formula? Should we delete it or update/rename it to just reflect latest stellar-core. I don't think anyone is using it, so maybe deleting makes sense?

We can delete it.

2023-10-11 19:04 UTC, sisuresh commented
> > @leighmcculloch what should we do about the `StellarCoreFuturenet` formula? Should we delete it or update/rename it to just reflect latest stellar-core. I don't think anyone is using it, so maybe deleting makes sense?
> 
> We can delete it.

Deleted. Thanks.

2023-10-11 19:13 UTC, leighmcculloch approved these changes

2023-10-11 19:21 UTC, merged